### ISSUE TITLE
Filter comparison not working

### ISSUE THREAD

**Issue by SivaMaplelabs** [vmware/hillview#443] opened 2018-10-08 10:52 UTC
![filtercompare-0](https://user-images.githubusercontent.com/22631594/46605156-31cc6d00-cb16-11e8-908f-9d8527cb5518.PNG)
![filtercompare](https://user-images.githubusercontent.com/22631594/46605166-398c1180-cb16-11e8-8d8c-c06dbb53ea0f.PNG)

**Comment by mbudiu-vmw** [comment] 2018-10-09 20:19
I cannot reproduce this bug. Can you give a sequence of steps needed to reproduce it - ideally on a dataset we can use too?
This may be an issue with the timezone; if the UI timezone is not the same as the server timezone then the date interpretation may be different.

**Comment by mbudiu-vmw** [comment] 2018-10-09 20:20
BTW: the date problem is tracked with #411

**Comment by SivaMaplelabs** [comment] 2018-10-10 05:13
@mbudiu-vmw Following are the steps to reproduce.
1. Load the system logs
2. Show Time
3. Select Compare in the Filter tab
4. Choose
    Column - "Time"
    Value -  "Some timestamp value from the table"
    Compare -  "=="
5. Issue will reproduce

**Comment by mbudiu-vmw** [comment] 2018-10-10 17:37
There are two problems:
- why is the system displaying NaN for the date you  selected? I will add some more validation to the input.
- why the filter returns empty. This one is tricky: what happens is that the actual timestamp has more decimals, but the display only shows some of them. So if you try to do an exact comparison it fails. This is the same problem as comparing two doubles - in general you should not compare doubles for equality. The solution may be to add an additional comparison "close to" for timestamps, where we allow a narrow range of values.

**Comment by mbudiu-vmw** [comment] 2019-09-17 23:29
I think this was fixed by #539

**Closed by mbudiu-vmw** 2019-09-17 23:29 UTC
Labels: fixed
